### ISSUE TITLE
Basic question about platform and goals

### ISSUE THREAD

**Issue by David263** [workshopper/learnyounode#303]
I got curious about recent technology and have been reading the websites for node.js, Jekyll, express.js, io.js, npm, async, gulp, and a lot more. Most of these websites don't bother describing what the product actually does. Most of them give examples of command-line usage that use Linux pathnames and command style. Not one of these websites says that it requires Linux for operation, or won't operate on Windows. And yet there are no Windows-style examples, and frequent mention of the need to install Rails, python, V8 through Chrome, or some other obscure or specific programming language or framework that really powers the product.

As an outsider, and a retired software and web engineer with 40 years of experience, I find all this very confusing.

I know I'm posting this in the wrong place, but I can't find any right place for wondering why there is so much duplication of applications to make easier the basic operators of programming, web implementation, system building, dependency management, etc. And yet there is no easy, error-free framework for creating a complete, simple Bootstrap-style website. I had to invent that myself out of PHP and Javascript.

I even found a wonderful essay ("Why we should stop using Grunt & Gulp", http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/) that reflects my own wonder at the complexities and limitations of all this much-hyped new and specialized technology.

I see the value of all this re-hashing and community-building in creating jobs, but I'm sure I"m missing something here if there is more to it than that.

I appreciate the elegance of constructing a server in a few short lines of code. But small and functional webservers like Mongoose have been around for a long time, always offering an alternative to the Apache or IIS giants.

Like most of you, I have developed lots of tools of my own, whether for locking small informal databases, writing a website, or whatever other task needed design or implementation. But I don't tell everyone I have the perfect and most elegant solution to every technical problem  Why are these new technologies so wildly promoted as the solution to everything? I don't get it.

**Comment by martinheidegger** [comment]
My 2cnt.

We are all learning. It is intimidating for me to learn C to a degree that I can write something like https://github.com/cesanta/mongoose but I feel confident doing a same or similar thing in Node.js. The reason for this is:

1. Habits: I am used to JavaScript and its quirks
2. Comfort: I am used to not-needing-to-deal with GarbageCollection and various other things that platform takes care from me. My node.js stuff usually "just-works" (tm) where-else I often fight the dependencies when I need to deal with c code, java, or almost any other language for that matter.
3. Infrastructure: `npm` before v3 was a rock-solid beast. As a result many-many packages have been created. Granted: Not as many as in C but still a quite respectable size and I rarely had any problems with versioning or something like that.
4. Tools: I can use quite a bit of the tools that i use for server development also for client-side which disrupts my work-environment less and I feel to be more productive.

Now: Since we write the stuff again we probably run into the same problems that hords of other developers in different languages ran into as well. As a result we had new ideas to old approaches that in some cases were better than those in the other languages.

Of course there has been a tremendous amount of work been put in "old platforms" (nodejs isn't as young as it used to be) and I am sure in many ways the C code might be superior but it is comfortable to see JavaScript doing those games.

Well, I hope this answers your question a bit. I will close this issue here. If you feel like asking more questions http://github.com/nodeschool/discussions/issues might probably be a better place (this issue tracker is meant to be used for issues related to learnyounode) where you can get an answer faster.
