### ISSUE TITLE
Update Troubleshooting steps in README

### ISSUE THREAD

**Issue by sangeethakp** [workshopper/learnyounode#511]
While installing the learnyounode by executing **npm install learnyounode -g** ,
Mac OSX users come acrss the following error:

**Error: EMFILE on OSX when requiring lots of files**

Reason for this error is you can't require more than 255 files on OSX.

Fix: ulimit -n 2560
This command allows you to display and set resource limits for users.

I think this has to be updated in the README.
Thanks!

**Comment by martinheidegger** [comment]
@sangeethakp Thank you for posting this. It would be important to know your NPM & Nodejs version because I think this a problem of [npm](https://github.com/npm/npm/issues) that shouldn't be solved here. Could you create a new issue at [npm](https://github.com/npm/npm/issues/new) with more information about your system? (OS, NPM & Node version?)

**Comment by sangeethakp** [comment]
Node Version v0.10.36 
npm Version 1.4.28

**Comment by sangeethakp** [comment]
Will open a new issue in npm..thanks for the prompt reply!

**Comment by martinheidegger** [comment]
Awesome, let me close this issue for now.
