### ISSUE TITLE
HTTP Client: unclear instructions

### ISSUE THREAD

**Issue by jrpool** [workshopper/learnyounode#544]
The instructions ask for a program that makes an “HTTP GET request to a URL provided to you”. They don’t answer the question: “Provided by whom?” In this context, one might easily expect that “provided to you” means “provided to you by learnyounode”. But I see no indication of a URL that learnyounode will provide. If it does not mean that, then I think it should say “the URL of any web resource of your choosing”, instead of “a URL provided to you”. The Spanish instructions seem to omit “provided to you”, but most others seem to include it. What is the intended meaning?

**Comment by AnshulMalik** [comment]
It seems fine to me, it says `provided yo you as first command-line argument`
So it only means that you need not care about what the Url is, just assume, you will get the Url

But still, let me know how else it can be rephrased to make more sense.

**Comment by jrpool** [comment]
I understand your thought, but in my opinion "you" is the developer, not the user. If it said "provided to the user" or simply left that phrase out, I believe it would not create the misunderstanding that it created for me.

**Comment by jrpool** [comment]
I suggest changing “HTTP GET request to a URL provided to you” to “HTTP GET request to a specified URL”.

**Comment by AnshulMalik** [comment]
That document to meant for the user, so still it looks fine to me :)

**Comment by kcpn** [comment]
But it is really provided to you (as the developer) by learnyounode.. isn't it?
At least it's what I understand..

`Write a program that performs an HTTP GET request to a URL provided to you  
as the first command-line argument.`

which means you just need to call `process.argv[2]`, since it's already there as `the first command-line argument`

if you don't get the url provided by the workshop (or get `undefined` when you call for it), you might want to reload the workshop again, it happened to me too once and it started working again when i reload it.

**Comment by jrpool** [comment]
The program performs the request. The program is not “you”. If a URL was provided to you, then you could hard-code that URL into the GET request. But it wasn’t. You don’t know it. So it is incorrect to say “provided to you”. It would be correct to say “Write a program that performs an HTTP GET request to the URL specified by the first command-line argument.”

**Comment by AnshulMalik** [comment]
Yeah, I get it now! Thanks @jrpool. 
This look good
> Write a program that performs an HTTP GET request to the URL specified by the first command-line argument

**Comment by shanmukhateja** [comment]
This issue can be closed as it seems to have been resolved.
