### ISSUE TITLE
Exc. 10 & 11 (Time/HTTP server) unable to connect to localhost

### ISSUE THREAD

**Issue by aaronArinder** [workshopper/learnyounode#549]
For those two exercises, I'm getting an error (even with the solution's code) saying that there was a problem connecting to the localhost: connect ECONNREFUSED.

I'm on OSX 10.11.6.

Edit: also, I killed all node processes to doublecheck that there weren't any background processes mucking it up.

**Comment by AnshulMalik** [comment]
Hey, sorry for the late response. Can you please tell which exercise you got this error and the script you were running?

**Comment by SunLeaves** [comment]
I meet this problem in exercise Time Server.  I run the code on a Cloud IDE，which is similar to the Cloud 9 suggested by FreeCodeCamp. 
It seems that the problem is caused by the command **learnyounode run/verify program.js** .I guess this command will use a port，but the enviroment doesn't permit. So even if you use the solution code, error occurs.

**Comment by AnshulMalik** [comment]
I'll have a look. Thanks @SunLeaves

**Comment by aaronArinder** [comment]
Oh man, sorry @AnshulMalik, I missed your reply. It looks like @SunLeaves knows what's up.

**Comment by th-santos** [comment]
I can not see @sunleaves comment. I guess it was deleted.
Could you guys explain how to solve this problem? Tks!

**Comment by floh79** [comment]
Hello, I ran into that issue. Neither Exercise 10 nor 11 is working for me because of ECONNREFUSED error:
  ✗  Error connecting to localhost:10456: connect ECONNREFUSED  
  127.0.0.1:10456

Any hint how to get it working?
- I tried with copy&pasted solution, still not working.
- I'm running linux, so I tried run learnyounode as root (thought it could be a permission issue because of opening ports), but still not working (same error).
- If I try with 'node program.js 8080' on Exercise 10 and try...
   - ... with browser with the url localhost:8080, there I see timestamp as expected.
   - ... with telnet using localhost and 127.0.0.1, both works fine too.

Somewhat fishy is going with learnyounode.

Would be great if someone could tell me what to do, or take a look into that and fix it.

Floh

**Comment by floh79** [comment]
SOLUTION:
The timeout is too tight if your machine is not fast (like mine since its running as VM on weak laptop).

Either you buy a faster PC/Laptop, or just do as following (disclaimer: be careful, I won't take responsibility if any nasty thing happens. So you're doing that at your own risk.):

If you go to these files and increase timeout from 500ms to 5000ms, then this should fix this issue.
As for Exercise 10, its in following path (if you're running linux):
/usr/local/lib/node_modules/learnyounode/exercises/time_server
As for Exercise 11, its in following path (if you're running linux):
/usr/local/lib/node_modules/learnyounode/exercises/http_file_server

There is a line in exercise.js:
  setTimeout(query.bind(this, mode), 500)
just add an zero so it looks like:
  setTimeout(query.bind(this, mode), 5000)

That helped me. :)

Floh

**Comment by aaronArinder** [comment]
That seems legit; solid sleuthing, @floh79. Closing.
