### ISSUE TITLE
HTTP UPPERCASERER doesn't require POST request

### ISSUE THREAD

**Issue by MarkJessop** [workshopper/learnyounode#76]
I've just completed the lesson HTTP UPPERCASERER where it asks for the HTTP server to only receive POST requests.  However the solution doesn't require the server to filter out non POST requests.  I believe the solution should send a GET request to see if the server is filtering out non POST requests

**Comment by Laoujin** [comment]
I want to add this functionality but after several attempts I'm not sure how this could be implemented. (There is a reason I'm doing these exercises...)

Is POST vs GET not checked because it would be awfully difficult to do or can someone give me some pointers about how to implement it? (has something similar been done somewhere else, or where should I start looking?)

**Comment by hughrawlinson** [comment]
Came here to say this too.

@Laoujin: It is somewhat difficult to check actually, because the expected behaviour for a non-POST request to the server is not defined in the question: "Write an HTTP server that only accepts POST requests...". You could just do the same request as exists in the verification with a GET instead of a POST and check that it does something other than return the body as upper case, but I think perhaps the question needs editing to define behaviour for other methods. Something like "If a request is made that isn't a post, you should return a 400 error", which would teach the user a bit about setting HTTP headers in node.

**Comment by piannaf** [comment]
@foragerr mentions in #285 there exists a [TODO for this exact issue](https://github.com/workshopper/learnyounode/blob/master/exercises/http_uppercaserer/exercise.js#L65)

I'm working on a [PR](https://github.com/piannaf/learnyounode/tree/http_uppercaser-post-only) now.

**Comment by hughrawlinson** [comment]
@piannaf Awesome :)

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
